# Erik Petrosyan ©
version: '3.8'

services:
    shtem-web:
        image: ${IMG}:${TAG}
        user: erik:erik
        deploy:
            replicas: 1
        environment:
            - GIN_MODE=${MODE}
        networks:
            - erik_internal_net
        command: ./cmd/web/app --cfg /run/secrets/web_shtem_app_cfg

secrets:
    web_shtem_app_cfg:
        name: web_shtem_app_cfg_v2
        file: ${DIR}/secrets.json

networks:
    erik_internal_net:
        driver: overlay
