// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors int32

const (
	Errors_ERR_UNKNOWN          Errors = 0
	Errors_ERR_ACCESS_TOKEN     Errors = 1
	Errors_ERR_METADATA         Errors = 2
	Errors_ERR_FILE_KEY         Errors = 3
	Errors_ERR_FILE_GROUP       Errors = 4
	Errors_ERR_FILE_SIZE        Errors = 5
	Errors_ERR_STREAM_DATA_LOSS Errors = 6
	Errors_ERR_STREAM_TIME_OUT  Errors = 7
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0: "ERR_UNKNOWN",
		1: "ERR_ACCESS_TOKEN",
		2: "ERR_METADATA",
		3: "ERR_FILE_KEY",
		4: "ERR_FILE_GROUP",
		5: "ERR_FILE_SIZE",
		6: "ERR_STREAM_DATA_LOSS",
		7: "ERR_STREAM_TIME_OUT",
	}
	Errors_value = map[string]int32{
		"ERR_UNKNOWN":          0,
		"ERR_ACCESS_TOKEN":     1,
		"ERR_METADATA":         2,
		"ERR_FILE_KEY":         3,
		"ERR_FILE_GROUP":       4,
		"ERR_FILE_SIZE":        5,
		"ERR_STREAM_DATA_LOSS": 6,
		"ERR_STREAM_TIME_OUT":  7,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

type CachePolicy int32

const (
	CachePolicy_CACHE_POLICY_UNSPECIFIED CachePolicy = 0
	CachePolicy_CACHE_POLICY_NEVER       CachePolicy = 1
	CachePolicy_CACHE_POLICY_MINIMAL     CachePolicy = 2
	CachePolicy_CACHE_POLICY_MEDIUM      CachePolicy = 3
	CachePolicy_CACHE_POLICY_MAXIMAL     CachePolicy = 4
)

// Enum value maps for CachePolicy.
var (
	CachePolicy_name = map[int32]string{
		0: "CACHE_POLICY_UNSPECIFIED",
		1: "CACHE_POLICY_NEVER",
		2: "CACHE_POLICY_MINIMAL",
		3: "CACHE_POLICY_MEDIUM",
		4: "CACHE_POLICY_MAXIMAL",
	}
	CachePolicy_value = map[string]int32{
		"CACHE_POLICY_UNSPECIFIED": 0,
		"CACHE_POLICY_NEVER":       1,
		"CACHE_POLICY_MINIMAL":     2,
		"CACHE_POLICY_MEDIUM":      3,
		"CACHE_POLICY_MAXIMAL":     4,
	}
)

func (x CachePolicy) Enum() *CachePolicy {
	p := new(CachePolicy)
	*p = x
	return p
}

func (x CachePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CachePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[1].Descriptor()
}

func (CachePolicy) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[1]
}

func (x CachePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CachePolicy.Descriptor instead.
func (CachePolicy) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

type ProvideFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	CachePolicy   CachePolicy            `protobuf:"varint,4,opt,name=cache_policy,json=cachePolicy,proto3,enum=proto.storage.CachePolicy" json:"cache_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideFileRequest) Reset() {
	*x = ProvideFileRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideFileRequest) ProtoMessage() {}

func (x *ProvideFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideFileRequest.ProtoReflect.Descriptor instead.
func (*ProvideFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ProvideFileRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProvideFileRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ProvideFileRequest) GetCachePolicy() CachePolicy {
	if x != nil {
		return x.CachePolicy
	}
	return CachePolicy_CACHE_POLICY_UNSPECIFIED
}

type ProvideFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideFileResponse) Reset() {
	*x = ProvideFileResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideFileResponse) ProtoMessage() {}

func (x *ProvideFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideFileResponse.ProtoReflect.Descriptor instead.
func (*ProvideFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ProvideFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ProvideFileResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	CachePolicy   CachePolicy            `protobuf:"varint,3,opt,name=cache_policy,json=cachePolicy,proto3,enum=proto.storage.CachePolicy" json:"cache_policy,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoreFileRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreFileRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StoreFileRequest) GetCachePolicy() CachePolicy {
	if x != nil {
		return x.CachePolicy
	}
	return CachePolicy_CACHE_POLICY_UNSPECIFIED
}

func (x *StoreFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *StoreFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *StoreFileRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StoreFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StoreFileResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\rproto.storage\"{\n" +
	"\x12ProvideFileRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12=\n" +
	"\fcache_policy\x18\x04 \x01(\x0e2\x1a.proto.storage.CachePolicyR\vcachePolicy\"A\n" +
	"\x13ProvideFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc2\x01\n" +
	"\x10StoreFileRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12=\n" +
	"\fcache_policy\x18\x03 \x01(\x0e2\x1a.proto.storage.CachePolicyR\vcachePolicy\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\")\n" +
	"\x11StoreFileResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total*\xad\x01\n" +
	"\x06Errors\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ERR_ACCESS_TOKEN\x10\x01\x12\x10\n" +
	"\fERR_METADATA\x10\x02\x12\x10\n" +
	"\fERR_FILE_KEY\x10\x03\x12\x12\n" +
	"\x0eERR_FILE_GROUP\x10\x04\x12\x11\n" +
	"\rERR_FILE_SIZE\x10\x05\x12\x18\n" +
	"\x14ERR_STREAM_DATA_LOSS\x10\x06\x12\x17\n" +
	"\x13ERR_STREAM_TIME_OUT\x10\a*\x90\x01\n" +
	"\vCachePolicy\x12\x1c\n" +
	"\x18CACHE_POLICY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CACHE_POLICY_NEVER\x10\x01\x12\x18\n" +
	"\x14CACHE_POLICY_MINIMAL\x10\x02\x12\x17\n" +
	"\x13CACHE_POLICY_MEDIUM\x10\x03\x12\x18\n" +
	"\x14CACHE_POLICY_MAXIMAL\x10\x042\xb8\x01\n" +
	"\fServiceFiles\x12V\n" +
	"\vProvideFile\x12!.proto.storage.ProvideFileRequest\x1a\".proto.storage.ProvideFileResponse0\x01\x12P\n" +
	"\tStoreFile\x12\x1f.proto.storage.StoreFileRequest\x1a .proto.storage.StoreFileResponse(\x01B\x0fZ\rproto/storageb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_proto_goTypes = []any{
	(Errors)(0),                 // 0: proto.storage.Errors
	(CachePolicy)(0),            // 1: proto.storage.CachePolicy
	(*ProvideFileRequest)(nil),  // 2: proto.storage.ProvideFileRequest
	(*ProvideFileResponse)(nil), // 3: proto.storage.ProvideFileResponse
	(*StoreFileRequest)(nil),    // 4: proto.storage.StoreFileRequest
	(*StoreFileResponse)(nil),   // 5: proto.storage.StoreFileResponse
}
var file_storage_proto_depIdxs = []int32{
	1, // 0: proto.storage.ProvideFileRequest.cache_policy:type_name -> proto.storage.CachePolicy
	1, // 1: proto.storage.StoreFileRequest.cache_policy:type_name -> proto.storage.CachePolicy
	2, // 2: proto.storage.ServiceFiles.ProvideFile:input_type -> proto.storage.ProvideFileRequest
	4, // 3: proto.storage.ServiceFiles.StoreFile:input_type -> proto.storage.StoreFileRequest
	3, // 4: proto.storage.ServiceFiles.ProvideFile:output_type -> proto.storage.ProvideFileResponse
	5, // 5: proto.storage.ServiceFiles.StoreFile:output_type -> proto.storage.StoreFileResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
